[package]
name = "testing"
version = "0.1.0"
authors = ["Seokju Na <seokju.me@gmail.com"]
edition = "2021"
rust-version = "1.57"

[dependencies]
nanoid = "0.4.0"
run_script = "^0.9.0"
eventstore = { path = "../eventstore" }
