[package]
name = "git-utils"
version = "0.1.0"
authors = ["Seokju Na <seokju.me@gmail.com"]
edition = "2021"
rust-version = "1.57"

[dependencies]
git2 = "0.13.25"
common = { path = "../common" }

[dev-dependencies]
testing = { path = "../testing" }
