/*
 Generated by typeshare 1.7.0
*/

export enum TaskStatus {
	Backlog = "BACKLOG",
	Queue = "QUEUE",
	InProgress = "IN_PROGRESS",
	Done = "DONE",
}

export interface Task {
	id: string;
	title: string;
	body?: string;
	status: TaskStatus;
	createdAt: string;
	updatedAt: string;
}

export type TaskCommand =
	| { name: "task.create", data: {
	id: string;
	title: string;
	status?: TaskStatus;
}}
	| { name: "task.updateTitle", data: {
	id: string;
	title: string;
}}
	| { name: "task.updateStatus", data: {
	id: string;
	status: TaskStatus;
}}
	| { name: "task.updateBody", data: {
	id: string;
	body?: string;
}}
	| { name: "task.delete", data: {
	id: string;
}};

