/*
 Generated by typeshare 1.7.0
*/

export type Version = number;

export type Timestamp = number;

export enum TaskStatus {
	Backlog = "BACKLOG",
	Queue = "QUEUE",
	InProgress = "IN_PROGRESS",
	Done = "DONE",
}

export interface Task {
	id: string;
	title: string;
	body?: string;
	status: TaskStatus;
	createdAt: Timestamp;
	updatedAt: Timestamp;
}

export interface Persisted<T> {
	aggregateId: string;
	version: Version;
	event: T;
}

export type DispatchMessage = 
	| { name: "task.persisted", data: {
	events: Persisted<TaskEvent>[];
}};

export type TaskEvent = 
	| { name: "task.created", data: {
	id: string;
	title: string;
	body?: string;
	status: TaskStatus;
}}
	| { name: "task.titleUpdated", data: {
	title: string;
}}
	| { name: "task.statusUpdated", data: {
	status: TaskStatus;
}}
	| { name: "task.bodyUpdated", data: {
	body?: string;
}}
	| { name: "task.deleted", data: {
}};

export type TaskCommand = 
	| { name: "task.create", data: {
	id: string;
	title: string;
	status?: TaskStatus;
}}
	| { name: "task.updateTitle", data: {
	id: string;
	title: string;
}}
	| { name: "task.updateStatus", data: {
	id: string;
	status: TaskStatus;
}}
	| { name: "task.updateBody", data: {
	id: string;
	body?: string;
}}
	| { name: "task.delete", data: {
	id: string;
}};

