name: ci
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-ci
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter="*" check
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter="*" typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter="*" test
  rust_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.75.0"
          override: true
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            app/
            core/
            testing/
      - run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - run: cargo clippy --workspace
  rust_test:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - host: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.75.0"
          override: true
          target: ${{ matrix.settings.target }}
      - if: matrix.settings.host == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            app/
            core/
            testing/
      - run: cargo test --workspace
