name: CI
on: [pull_request]
jobs:
  typecheck-lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use nodejs v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            **/*.tsbuildinfo
            **/.eslintcache
          key: typecheck-lint-cache-${{ hashFiles('**/*.tsbuildinfo') }}-${{ hashFiles('**/.eslintcache') }}
          restore-keys: |
            typecheck-lint-cache-
      - name: run yarn install
        run: yarn install --immutable --immutable-cache
      - name: lint
        run: yarn lint
      - name: typecheck
        run: yarn typecheck
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use nodejs v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: use rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: cache cargo
        uses: actions/cache@v2
        env:
          cache-name: cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-
            ${{ matrix.platform }}-stable-
            ${{ matrix.platform }}-
      - name: cache target
        uses: actions/cache@v2
        env:
          cache-name: target
        with:
          path: target
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-
            ${{ matrix.platform }}-stable-
            ${{ matrix.platform }}-
      - name: run yarn install
        run: yarn install --immutable --immutable-cache
      - name: webview build
        run: yarn build
      - name: test
        run: yarn test
      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
