name: CI
on: [pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use nodejs v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: use rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rust cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: run yarn install
        run: yarn install --immutable --immutable-cache
      - name: test
        run: yarn test
      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
